// YouTube's `defaultLanguage` accepts BCP-47 codes. Common ones pinned to top.

export interface YouTubeLanguage {
  code: string; // BCP-47
  label: string;
}

export const PINNED_LANGUAGES: YouTubeLanguage[] = [
  { code: "en", label: "English" },
  { code: "fr", label: "Français" },
  { code: "es", label: "Español" },
];

export const ALL_LANGUAGES: YouTubeLanguage[] = [
  { code: "af", label: "Afrikaans" },
  { code: "sq", label: "Shqip (Albanian)" },
  { code: "am", label: "አማርኛ (Amharic)" },
  { code: "ar", label: "العربية (Arabic)" },
  { code: "hy", label: "Հայերեն (Armenian)" },
  { code: "az", label: "Azərbaycan (Azerbaijani)" },
  { code: "eu", label: "Euskara (Basque)" },
  { code: "be", label: "Беларуская (Belarusian)" },
  { code: "bn", label: "বাংলা (Bengali)" },
  { code: "bs", label: "Bosanski (Bosnian)" },
  { code: "bg", label: "Български (Bulgarian)" },
  { code: "my", label: "ဗမာ (Burmese)" },
  { code: "ca", label: "Català (Catalan)" },
  { code: "zh-CN", label: "中文 简体 (Chinese, Simplified)" },
  { code: "zh-TW", label: "中文 繁體 (Chinese, Traditional)" },
  { code: "hr", label: "Hrvatski (Croatian)" },
  { code: "cs", label: "Čeština (Czech)" },
  { code: "da", label: "Dansk (Danish)" },
  { code: "nl", label: "Nederlands (Dutch)" },
  { code: "en-GB", label: "English (United Kingdom)" },
  { code: "en-US", label: "English (United States)" },
  { code: "et", label: "Eesti (Estonian)" },
  { code: "fil", label: "Filipino" },
  { code: "fi", label: "Suomi (Finnish)" },
  { code: "fr-CA", label: "Français (Canada)" },
  { code: "fr-FR", label: "Français (France)" },
  { code: "gl", label: "Galego (Galician)" },
  { code: "ka", label: "ქართული (Georgian)" },
  { code: "de", label: "Deutsch (German)" },
  { code: "el", label: "Ελληνικά (Greek)" },
  { code: "gu", label: "ગુજરાતી (Gujarati)" },
  { code: "iw", label: "עברית (Hebrew)" },
  { code: "hi", label: "हिन्दी (Hindi)" },
  { code: "hu", label: "Magyar (Hungarian)" },
  { code: "is", label: "Íslenska (Icelandic)" },
  { code: "id", label: "Bahasa Indonesia" },
  { code: "ga", label: "Gaeilge (Irish)" },
  { code: "it", label: "Italiano" },
  { code: "ja", label: "日本語 (Japanese)" },
  { code: "kn", label: "ಕನ್ನಡ (Kannada)" },
  { code: "kk", label: "Қазақ (Kazakh)" },
  { code: "km", label: "ភាសាខ្មែរ (Khmer)" },
  { code: "ko", label: "한국어 (Korean)" },
  { code: "ky", label: "Кыргыз (Kyrgyz)" },
  { code: "lo", label: "ລາວ (Lao)" },
  { code: "lv", label: "Latviešu (Latvian)" },
  { code: "lt", label: "Lietuvių (Lithuanian)" },
  { code: "lb", label: "Lëtzebuergesch (Luxembourgish)" },
  { code: "mk", label: "Македонски (Macedonian)" },
  { code: "ms", label: "Bahasa Melayu (Malay)" },
  { code: "ml", label: "മലയാളം (Malayalam)" },
  { code: "mt", label: "Malti (Maltese)" },
  { code: "mr", label: "मराठी (Marathi)" },
  { code: "mn", label: "Монгол (Mongolian)" },
  { code: "ne", label: "नेपाली (Nepali)" },
  { code: "no", label: "Norsk" },
  { code: "ps", label: "پښتو (Pashto)" },
  { code: "fa", label: "فارسی (Persian)" },
  { code: "pl", label: "Polski (Polish)" },
  { code: "pt-BR", label: "Português (Brasil)" },
  { code: "pt-PT", label: "Português (Portugal)" },
  { code: "pa", label: "ਪੰਜਾਬੀ (Punjabi)" },
  { code: "ro", label: "Română (Romanian)" },
  { code: "ru", label: "Русский (Russian)" },
  { code: "sr", label: "Српски (Serbian)" },
  { code: "si", label: "සිංහල (Sinhala)" },
  { code: "sk", label: "Slovenčina (Slovak)" },
  { code: "sl", label: "Slovenščina (Slovenian)" },
  { code: "es-ES", label: "Español (España)" },
  { code: "es-419", label: "Español (Latinoamérica)" },
  { code: "sw", label: "Kiswahili (Swahili)" },
  { code: "sv", label: "Svenska (Swedish)" },
  { code: "ta", label: "தமிழ் (Tamil)" },
  { code: "te", label: "తెలుగు (Telugu)" },
  { code: "th", label: "ไทย (Thai)" },
  { code: "tr", label: "Türkçe (Turkish)" },
  { code: "uk", label: "Українська (Ukrainian)" },
  { code: "ur", label: "اردو (Urdu)" },
  { code: "uz", label: "Oʻzbek (Uzbek)" },
  { code: "vi", label: "Tiếng Việt (Vietnamese)" },
  { code: "cy", label: "Cymraeg (Welsh)" },
  { code: "zu", label: "isiZulu (Zulu)" },
];

// Mapping from Deepgram language name / code → YouTube BCP-47 code
export function pickYouTubeLanguage(detected: string | undefined | null): string {
  if (!detected) return "en";
  const d = detected.trim().toLowerCase();
  const map: Record<string, string> = {
    en: "en", english: "en",
    fr: "fr", french: "fr", français: "fr",
    "fr-ca": "fr-CA", "fr-fr": "fr-FR",
    es: "es", spanish: "es", español: "es",
    "es-419": "es-419", "es-es": "es-ES",
    pt: "pt-BR", portuguese: "pt-BR",
    de: "de", german: "de", deutsch: "de",
    it: "it", italian: "it",
    ja: "ja", japanese: "ja",
    ko: "ko", korean: "ko",
    "zh": "zh-CN", chinese: "zh-CN",
    ar: "ar", arabic: "ar",
    hi: "hi", hindi: "hi",
    nl: "nl", dutch: "nl",
    pl: "pl", polish: "pl",
    ru: "ru", russian: "ru",
    tr: "tr", turkish: "tr",
    sv: "sv", swedish: "sv",
    vi: "vi", vietnamese: "vi",
    uk: "uk", ukrainian: "uk",
    id: "id", indonesian: "id",
    th: "th", thai: "th",
    cs: "cs", czech: "cs",
    da: "da", danish: "da",
    fi: "fi", finnish: "fi",
    el: "el", greek: "el",
    he: "iw", hebrew: "iw",
    no: "no", norwegian: "no",
    ro: "ro", romanian: "ro",
  };
  if (map[d]) return map[d];
  // Fallback: try first two chars
  const short = d.slice(0, 2);
  return map[short] ?? "en";
}
